# Generated by Django 4.2.3 on 2023-08-03 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boomnet', '0003_remove_profile_nickname_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='boomnet.post'),
            preserve_default=False,
        ),
    ]
