# Generated by Django 4.2.3 on 2023-08-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boomnet', '0004_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
