# Generated by Django 4.2.3 on 2023-08-14 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boomnet', '0004_vote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Following',
        ),
    ]
