# Generated by Django 4.2.3 on 2023-08-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boomnet', '0005_alter_comment_created_at_alter_profile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='info',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
