# Generated by Django 4.2.3 on 2023-08-19 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boomnet', '0007_profile_followers_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
    ]
