# Generated by Django 4.2.3 on 2023-08-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boomnet', '0010_remove_post_updated_at_topic_post_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='topic_images'),
        ),
    ]
